"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const authSeller_1 = __importDefault(require("../App/middlewares/authSeller"));
const authUser_1 = __importDefault(require("../App/middlewares/authUser"));
const uploadImage_1 = __importDefault(require("../App/middlewares/uploadImage"));
const createProduct_1 = __importDefault(require("../App/useCases/product/createProduct"));
const deleteProduct_1 = __importDefault(require("../App/useCases/product/deleteProduct"));
const listComments_1 = __importDefault(require("../App/useCases/product/listComments"));
const listProduct_1 = __importDefault(require("../App/useCases/product/listProduct"));
const listProducts_1 = __importDefault(require("../App/useCases/product/listProducts"));
const listProductsBySeller_1 = __importDefault(require("../App/useCases/product/listProductsBySeller"));
const updateProduct_1 = __importDefault(require("../App/useCases/product/updateProduct"));
const createComment_1 = __importDefault(require("../App/useCases/user/createComment"));
const replyRating_1 = __importDefault(require("../App/useCases/seller/replyRating"));
const removeComment_1 = __importDefault(require("../App/useCases/user/removeComment"));
const removeReplyRating_1 = __importDefault(require("../App/useCases/seller/removeReplyRating"));
const productRoutes = express_1.default.Router();
productRoutes.get('/products', listProducts_1.default);
productRoutes.get('/product/:id', listProduct_1.default);
productRoutes.get('/seller/:sellerId', authUser_1.default, listProductsBySeller_1.default);
productRoutes.get('/product/:id/comments', listComments_1.default);
productRoutes.post('/product/:id/comment/new', authUser_1.default, createComment_1.default);
productRoutes.post('/product/:id/comment/:commentId', authSeller_1.default, replyRating_1.default);
productRoutes.post('/product/new', authSeller_1.default, uploadImage_1.default.array('images'), createProduct_1.default);
productRoutes.post('/product/:id', authSeller_1.default, uploadImage_1.default.array('images'), updateProduct_1.default);
productRoutes.delete('/product/:id/comment', authUser_1.default, removeComment_1.default);
productRoutes.delete('/product/:id/comment/:commentId/reply/replyId', authSeller_1.default, removeReplyRating_1.default);
productRoutes.delete('/product/:id', authSeller_1.default, deleteProduct_1.default);
exports.default = productRoutes;
