"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const sellerRoutes = express_1.default.Router();
const uploadImage_1 = __importDefault(require("../App/middlewares/uploadImage"));
const authSeller_1 = __importDefault(require("../App/middlewares/authSeller"));
const authUser_1 = __importDefault(require("../App/middlewares/authUser"));
const listSellers_1 = __importDefault(require("../App/useCases/seller/listSellers"));
const listSeller_1 = __importDefault(require("../App/useCases/seller/listSeller"));
const createSeller_1 = __importDefault(require("../App/useCases/seller/createSeller"));
const loginSeller_1 = __importDefault(require("../App/useCases/seller/loginSeller"));
const forgotPasswordSeller_1 = __importDefault(require("../App/useCases/seller/forgotPasswordSeller"));
const verifyTokenIsValid_1 = __importDefault(require("../App/useCases/seller/verifyTokenIsValid"));
const replyRating_1 = __importDefault(require("../App/useCases/seller/replyRating"));
const updateSeller_1 = __importDefault(require("../App/useCases/seller/updateSeller"));
const updateContactsSeller_1 = __importDefault(require("../App/useCases/seller/updateContactsSeller"));
const changeSellerPassword_1 = __importDefault(require("../App/useCases/seller/changeSellerPassword"));
const uploadSellerProfile_1 = __importDefault(require("../App/useCases/seller/uploadSellerProfile"));
const removeReplyRating_1 = __importDefault(require("../App/useCases/seller/removeReplyRating"));
const deleteSeller_1 = __importDefault(require("../App/useCases/seller/deleteSeller"));
sellerRoutes.get('/sellers', authUser_1.default, listSellers_1.default);
sellerRoutes.get('/seller', authSeller_1.default, listSeller_1.default);
sellerRoutes.post('/sign-up/seller', createSeller_1.default);
sellerRoutes.post('/sign-in/seller', loginSeller_1.default);
sellerRoutes.post('/forgotpassword/seller', forgotPasswordSeller_1.default);
sellerRoutes.post('/verifytoken', verifyTokenIsValid_1.default);
sellerRoutes.post('/rating/:id', authSeller_1.default, replyRating_1.default);
sellerRoutes.patch('/seller/update', authSeller_1.default, updateSeller_1.default);
sellerRoutes.patch('/seller/contact', authSeller_1.default, updateContactsSeller_1.default);
sellerRoutes.patch('/resetpassword/seller/:token', changeSellerPassword_1.default);
sellerRoutes.patch('/seller/upload-profile', authSeller_1.default, uploadImage_1.default.single('avatar'), uploadSellerProfile_1.default);
sellerRoutes.delete('/comment/:id/reply', authSeller_1.default, removeReplyRating_1.default);
sellerRoutes.delete('/seller/delete', authSeller_1.default, deleteSeller_1.default);
exports.default = sellerRoutes;
